# Generated by Django 3.2.12 on 2022-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watch_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish',
            field=models.ManyToManyField(blank=True, related_name='wish_users', to='movies.Movie'),
        ),
    ]
