# Generated by Django 3.2.12 on 2022-05-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
