# Generated by Django 3.2.12 on 2022-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='korean_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
