# Generated by Django 3.2.12 on 2022-05-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
