# Generated by Django 3.2.12 on 2022-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_actor_korean_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
