# Generated by Django 3.2.12 on 2022-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
