# Generated by Django 3.2.12 on 2022-05-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20220522_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='character',
        ),
        migrations.AddField(
            model_name='cast',
            name='actor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='people.actor'),
            preserve_default=False,
        ),
    ]
