# Generated by Django 3.2.12 on 2022-05-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20220522_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='actor_id',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
