# Generated by Django 3.2.12 on 2022-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_director'),
        ('people', '0007_auto_20220522_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(through='people.Cast', to='movies.Movie'),
        ),
    ]
