# Generated by Django 3.2.12 on 2022-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_director'),
        ('people', '0008_actor_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='actor', through='people.Cast', to='movies.Movie'),
        ),
    ]
